
CREATE TABLE bike_rentals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  bikeId INT NOT NULL,
  rentedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiresAt TIMESTAMP NOT NULL,
  returnedAt TIMESTAMP NULL,
  status ENUM('RENTED','RETURNED','EXPIRED') DEFAULT 'RENTED',
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (bikeId) REFERENCES bikes(id)
);